{
  catppuccin = rec {
    variants = {
      mocha = {
        palette = rec {
          rosewater = "f5e0dc"; #f5e0dc
          flamingo = "f2cdcd"; #f2cdcd
          pink = "f5c2e7"; #f5c2e7
          mauve = "cba6f7"; #cba6f7
          red = "f38ba8"; #f38ba8
          maroon = "eba0ac"; #eba0ac
          peach = "fab387"; #fab387
          yellow = "f9e2af"; #f9e2af
          green = "a6e3a1"; #a6e3a1
          teal = "94e2d5"; #94e2d5
          sky = "89dceb"; #89dceb
          sapphire = "74c7ec"; #74c7ec
          blue = "89b4fa"; #89b4fa
          lavender = "b4befe"; #b4befe
          text = "cdd6f4"; #cdd6f4
          subtext1 = "bac2de"; #bac2de
          subtext0 = "a6adc8"; #a6adc8
          overlay2 = "9399b2"; #9399b2
          overlay1 = "7f849c"; #7f849c
          overlay0 = "6c7086"; #6c7086
          surface2 = "585b70"; #585b70
          surface1 = "45475a"; #45475a
          surface0 = "313244"; #313244
          base = "1e1e2e"; #1e1e2e
          mantle = "181825"; #181825
          crust = "11111b"; #11111b
          customBg = mantle;
          customFg = blue;
          customBtnHoverBg = blue;
          customBtnHoverFg = crust;
          customColorSlot1 = red;
          customColorSlot2 = pink;
          customBgAlt = crust;
          customFgAlt = customFg;
          customAccentPrimary = customFg;
          customAccentSecondary = customBtnHoverBg;
          customActiveTabBg = blue;
          customInactiveTabBg = surface0;
        };
        mode = "dark";
      };
      macchiato = {
        palette = rec {
          rosewater = "f5e0dc"; #f5e0dc
          flamingo = "f2cdcd"; #f2cdcd
          pink = "f5c2e7"; #f5c2e7
          mauve = "cba6f7"; #cba6f7
          red = "f38ba8"; #f38ba8
          maroon = "eba0ac"; #eba0ac
          peach = "fab387"; #fab387
          yellow = "f9e2af"; #f9e2af
          green = "a6e3a1"; #a6e3a1
          teal = "94e2d5"; #94e2d5
          sky = "89dceb"; #89dceb
          sapphire = "74c7ec"; #74c7ec
          blue = "89b4fa"; #89b4fa
          lavender = "b4befe"; #b4befe
          text = "cdd6f4"; #cdd6f4
          subtext1 = "bac2de"; #bac2de
          subtext0 = "a6adc8"; #a6adc8
          overlay2 = "9399b2"; #9399b2
          overlay1 = "7f849c"; #7f849c
          overlay0 = "6c7086"; #6c7086
          surface2 = "585b70"; #585b70
          surface1 = "45475a"; #45475a
          surface0 = "313244"; #313244
          base = "1e1e2e"; #1e1e2e
          mantle = "181825"; #181825
          crust = "11111b"; #11111b
          customBg = base;
          customFg = blue;
          customBtnHoverBg = blue;
          customBtnHoverFg = mantle;
          customColorSlot1 = red;
          customColorSlot2 = pink;
          customBgAlt = mantle;
          customFgAlt = customFg;
          customAccentPrimary = customFg;
          customAccentSecondary = customBtnHoverBg;
          customActiveTabBg = blue;
          customInactiveTabBg = surface0;
        };
        mode = "dark";
      };
      frappe = {
        palette = rec {
          rosewater = "f2d5cf"; #f2d5cf
          flamingo = "eebebe"; #eebebe
          pink = "f4b8e4"; #f4b8e4
          mauve = "ca9ee6"; #ca9ee6
          red = "e78284"; #e78284
          maroon = "ea999c"; #ea999c
          peach = "ef9f76"; #ef9f76
          yellow = "e5c890"; #e5c890
          green = "a6d189"; #a6d189
          teal = "81c8be"; #81c8be
          sky = "99d1db"; #99d1db
          sapphire = "85c1dc"; #85c1dc
          blue = "8caaee"; #8caaee
          lavender = "babbf1"; #babbf1
          text = "c6d0f5"; #c6d0f5
          subtext1 = "b5bfe2"; #b5bfe2
          subtext0 = "a5adce"; #a5adce
          overlay2 = "949cbb"; #949cbb
          overlay1 = "838ba7"; #838ba7
          overlay0 = "737994"; #737994
          surface2 = "626880"; #626880
          surface1 = "51576d"; #51576d
          surface0 = "414559"; #414559
          base = "303446"; #303446
          mantle = "292c3c"; #292c3c
          crust = "232634"; #232634
          customBg = base;
          customFg = blue;
          customBtnHoverBg = blue;
          customBtnHoverFg = mantle;
          customColorSlot1 = red;
          customColorSlot2 = pink;
          customBgAlt = mantle;
          customFgAlt = customFg;
          customAccentPrimary = customFg;
          customAccentSecondary = customBtnHoverBg;
          customActiveTabBg = blue;
          customInactiveTabBg = surface0;
        };
        mode = "dark";
      };
      latte = {
        palette = rec {
          rosewater = "dc8a78"; #dc8a78
          flamingo = "dd7878"; #dd7878
          pink = "ea76cb"; #ea76cb
          mauve = "8839ef"; #8839ef
          red = "d20f39"; #d20f39
          maroon = "e64553"; #e64553
          peach = "fe640b"; #fe640b
          yellow = "df8e1d"; #df8e1d
          green = "40a02b"; #40a02b
          teal = "179299"; #179299
          sky = "04a5e5"; #04a5e5
          sapphire = "209fb5"; #209fb5
          blue = "1e66f5"; #1e66f5
          lavender = "7287fd"; #7287fd
          text = "4c4f69"; #4c4f69
          subtext1 = "5c5f77"; #5c5f77
          subtext0 = "6c6f85"; #6c6f85
          overlay2 = "7c7f93"; #7c7f93
          overlay1 = "8c8fa1"; #8c8fa1
          overlay0 = "9ca0b0"; #9ca0b0
          surface2 = "acb0be"; #acb0be
          surface1 = "bcc0cc"; #bcc0cc
          surface0 = "ccd0da"; #ccd0da
          base = "eff1f5"; #eff1f5
          mantle = "e6e9ef"; #e6e9ef
          crust = "dce0e8"; #dce0e8
          customBg = base;
          customFg = blue;
          customBtnHoverBg = blue;
          customBtnHoverFg = mantle;
          customColorSlot1 = sky;
          customColorSlot2 = teal;
          customBgAlt = "181825"; #181825
          customFgAlt = customFg;
          customAccentPrimary = "303446"; #303446
          customAccentSecondary = customBtnHoverBg;
        };
        mode = "light";
      };
    };
    cognates = value: {
      selection = variants.${value}.palette.surface0;
      comment = variants.${value}.palette.surface2;
      color0 = variants.${value}.palette.red;
      color1 = variants.${value}.palette.maroon;
      color2 = variants.${value}.palette.yellow;
      color3 = variants.${value}.palette.blue;
      color4 = variants.${value}.palette.peach;
      color5 = variants.${value}.palette.lavender;
      color6 = variants.${value}.palette.flamingo;
      color7 = variants.${value}.palette.mauve;
      color8 = variants.${value}.palette.teal;
      color9 = variants.${value}.palette.rosewater;
      color10 = variants.${value}.palette.sapphire;
      color11 = variants.${value}.palette.pink;
      color12 = variants.${value}.palette.green;
      color13 = variants.${value}.palette.maroon;
      menu = variants.${value}.palette.customBtnHoverFg;
      nontext = variants.${value}.palette.overlay2;
      white = variants.${value}.palette.text;
      black = variants.${value}.palette.customBgAlt;

      failure = variants.${value}.palette.red;
      warning = variants.${value}.palette.yellow;
      active_accent1 = variants.${value}.palette.mauve;
      active_accent2 = variants.${value}.palette.rosewater;
      inactive_accent1 = variants.${value}.palette.lavender;
      inactive_accent2 = variants.${value}.palette.overlay0;
      text = variants.${value}.palette.text;
      fg = variants.${value}.palette.customFg;
      fg_field = variants.${value}.palette.surface0;
      bg = variants.${value}.palette.customBg;
      btn_hover_bg = variants.${value}.palette.customBtnHoverBg;
      btn_hover_bg2 = variants.${value}.palette.green;
      btn_hover_bg3 = variants.${value}.palette.mauve;
      btn_hover_bg4 = variants.${value}.palette.peach;
      btn_hover_bg5 = variants.${value}.palette.sky;
      btn_hover_fg = variants.${value}.palette.customBtnHoverFg;
      color_slot1 = variants.${value}.palette.customColorSlot1;
      color_slot2 = variants.${value}.palette.customColorSlot2;
      bg_alt = variants.${value}.palette.customBgAlt;
      text_alt = variants.${value}.palette.customFgAlt;
      accent_primary_alt = variants.${value}.palette.customAccentPrimary;
      accent_secondary_alt = variants.${value}.palette.customAccentSecondary;
      separator_mid = variants.${value}.palette.customFg;
    };
    props = {
      separator_left = "";
      separator_right = "";
      separator_mid = "";
      mascot = "󰄛";
    };
  };
  dracula = rec {
    variants = {
      standard = {
        palette = {
          background = "282a36"; #282a36
          currentLine = "44475a"; #44475a #selection
          foreground = "f8f8f2"; #f8f8f2
          comment = "6272a4"; #6272a4
          cyan = "8be9fd"; #8be9fd
          green = "50fa7b"; #50fa7b
          orange = "ffb86c"; #ffb86c
          pink = "ff79c6"; #ff79c6
          purple = "bd93f9"; #bd93f9
          red = "ff5555"; #ff5555
          yellow = "f1fa8c"; #f1fa8c
          bright_red = "FF6E6E"; #FF6E6E
          bright_green = "69FF94"; #69FF94
          bright_yellow = "FFFFA5"; #FFFFA5
          bright_blue = "D6ACFF"; #D6ACFF
          bright_magenta = "FF92DF"; #FF92DF
          bright_cyan = "A4FFFF"; #A4FFFF
          bright_white = "FFFFFF"; #FFFFFF
          menu = "21222C"; #21222C
          nontext = "3B4048"; #3B4048
          white = "ABB2BF"; #ABB2BF
          black = "191A21"; #191A21
        };
        mode = "dark";
      };
    };
    cognates = value: {
      selection = variants.${value}.palette.customSelection;
      comment = variants.${value}.palette.comment;
      color0 = variants.${value}.palette.red;
      color1 = variants.${value}.palette.white;
      color2 = variants.${value}.palette.bright_cyan;
      color3 = variants.${value}.palette.green;
      color4 = variants.${value}.palette.bright_magenta;
      color5 = variants.${value}.palette.purple;
      color6 = variants.${value}.palette.cyan;
      color7 = variants.${value}.palette.pink;
      color8 = variants.${value}.palette.bright_green;
      color9 = variants.${value}.palette.bright_yellow;
      color10 = variants.${value}.palette.bright_blue;
      color11 = variants.${value}.palette.bright_red;
      color12 = variants.${value}.palette.yellow;
      color13 = variants.${value}.palette.orange;
      menu = variants.${value}.palette.menu;
      nontext = variants.${value}.palette.nontext;
      white = variants.${value}.palette.white;
      black = variants.${value}.palette.black;

      failure = variants.${value}.palette.red;
      warning = variants.${value}.palette.yellow;
      active_accent1 = variants.${value}.palette.pink;
      active_accent2 = variants.${value}.palette.cyan;
      inactive_accent1 = variants.${value}.palette.comment;
      inactive_accent2 = variants.${value}.palette.currentLine;
      text = variants.${value}.palette.foreground;
      fg = variants.${value}.palette.foreground;
      fg_field = variants.${value}.palette.black;
      bg = variants.${value}.palette.background;
      btn_hover_bg = variants.${value}.palette.purple;
      btn_hover_bg2 = variants.${value}.palette.green;
      btn_hover_bg3 = variants.${value}.palette.pink;
      btn_hover_bg4 = variants.${value}.palette.cyan;
      btn_hover_bg5 = variants.${value}.palette.orange;
      btn_hover_fg = variants.${value}.palette.background;
      color_slot1 = variants.${value}.palette.pink;
      color_slot2 = variants.${value}.palette.comment;
      bg_alt = variants.${value}.palette.background;
      text_alt = variants.${value}.palette.foreground;
      accent_primary_alt = variants.${value}.palette.foreground;
      accent_secondary_alt = variants.${value}.palette.background;
      separator_mid = "a2b2e4";
    };
    props = {
      separator_left = "";
      separator_right = "";
      separator_mid = "";
      mascot = "󰭟";
    };
  };
  gruvbox = rec {
    variants = {
      dark = {
        palette = rec {
          bg = "282828"; #282828
          darkRed = "cc241d"; #cc241d
          red = "fb4934"; #fb4934
          darkGreen = "98971a"; #98971a
          green = "b8bb26"; #b8bb26
          darkYellow = "d79921"; #d79921
          yellow = "fabd2f"; #fabd2f
          darkBlue = "83a598"; #83a598
          blue = "458588"; #458588
          darkPurple = "b16286"; #b16286
          purple = "d3869b"; #d3869b
          darkGray = "928374"; #928374
          gray = "a89984"; #a89984
          darkAqua = "689d6a"; #689d6a
          aqua = "8ec07c"; #8ec07c
          fg = "ebdbb2"; #ebdbb2
          bg0_h = "1d2021"; #1d2021
          bg0 = "282828"; #282828
          bg1 = "3c3836"; #3c3836
          bg2 = "504945"; #504945
          bg3 = "665c54"; #665c54
          bg4 = "7c6f64"; #7c6f64
          orange = "d65d0e"; #d65d0e
          bg0_s = "32302f"; #32302f
          fg4 = "a89984"; #a89984
          fg3 = "bdae93"; #bdae93
          fg2 = "d5c4a1"; #d5c4a1
          fg1 = "ebdbb2"; #ebdbb2
          fg0 = "fbf1c7"; #fbf1c7
          darkOrange = "fe8019"; #fe8019
          bright_white = fg0;
          white = yellow;
        };
        mode = "dark";
      };
    };
    cognates = value: {
      inactive_bg = variants.${value}.palette.bg2;
      selection = variants.${value}.palette.bg0_s;
      comment = variants.${value}.palette.darkGray;
      color0 = variants.${value}.palette.darkRed;
      color1 = variants.${value}.palette.darkOrange;
      color2 = variants.${value}.palette.darkYellow;
      color3 = variants.${value}.palette.darkGreen;
      color4 = variants.${value}.palette.darkPurple;
      color5 = variants.${value}.palette.darkBlue;
      color6 = variants.${value}.palette.orange;
      color7 = variants.${value}.palette.red;
      color8 = variants.${value}.palette.green;
      color9 = variants.${value}.palette.yellow;
      color10 = variants.${value}.palette.blue;
      color11 = variants.${value}.palette.purple;
      color12 = variants.${value}.palette.aqua;
      color13 = variants.${value}.palette.bright_white;
      menu = variants.${value}.palette.bg0_s;
      nontext = variants.${value}.palette.bg4;
      white = variants.${value}.palette.white;
      black = variants.${value}.palette.bg;

      failure = variants.${value}.palette.red;
      warning = variants.${value}.palette.yellow;
      active_accent1 = variants.${value}.palette.blue;
      active_accent2 = variants.${value}.palette.purple;
      inactive_accent1 = variants.${value}.palette.gray;
      inactive_accent2 = variants.${value}.palette.darkGray;
      text = variants.${value}.palette.fg;
      fg = variants.${value}.palette.fg;
      fg_field = variants.${value}.palette.bg2;
      bg = variants.${value}.palette.bg;
      btn_hover_bg = variants.${value}.palette.gray;
      btn_hover_bg2 = variants.${value}.palette.green;
      btn_hover_bg3 = variants.${value}.palette.darkRed;
      btn_hover_bg4 = variants.${value}.palette.darkBlue;
      btn_hover_bg5 = variants.${value}.palette.purple;
      btn_hover_fg = variants.${value}.palette.bg;
      color_slot1 = variants.${value}.palette.darkOrange;
      color_slot2 = variants.${value}.palette.gray;
      bg_alt = variants.${value}.palette.bg;
      text_alt = variants.${value}.palette.fg;
      accent_primary_alt = variants.${value}.palette.bg;
      accent_secondary_alt = variants.${value}.palette.darkBlue;
      separator_mid = variants.${value}.palette.gray;
    };
    props = {
      separator_left = "";
      separator_right = "";
      separator_mid = "";
      mascot = "󰫴󰃔";
    };
  };
}
